# Generated by Django 4.2.7 on 2024-03-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MPD_Item_Number', models.CharField(default='null', max_length=255)),
                ('Task_Card_Number', models.CharField(default='null', max_length=255)),
                ('Related_Task_Card_Number', models.CharField(default='null', max_length=255)),
                ('AMM_Refrence', models.CharField(default='null', max_length=255)),
                ('CAT', models.CharField(default='null', max_length=255)),
                ('PGM', models.CharField(default='null', max_length=255)),
                ('Interval_Thres', models.CharField(default='null', max_length=255)),
                ('Interval_Repeat', models.CharField(default='null', max_length=255)),
                ('Task_Title', models.CharField(default='null', max_length=255)),
                ('Task_ATA', models.TextField(default='null')),
                ('Task', models.CharField(default='null', max_length=255)),
                ('Task_Description', models.TextField(default='null')),
                ('Zone', models.CharField(default='null', max_length=255)),
                ('Access', models.CharField(default='null', max_length=255)),
                ('Applicability_APL', models.CharField(default='null', max_length=255)),
                ('Applicability_ENG', models.CharField(default='null', max_length=255)),
                ('Man_Hour', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Acess_Hour', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Total_Hour', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Applicable_For_800', models.CharField(default='null', max_length=255)),
                ('Type', models.CharField(default='null', max_length=255)),
                ('Package', models.CharField(default='null', max_length=255)),
                ('Flight_Cycle_IntervalThres', models.FloatField(blank=True, null=True)),
                ('Flight_Cycle_Thres', models.CharField(blank=True, max_length=255, null=True)),
                ('Flight_Hours_IntervalThres', models.FloatField(blank=True, null=True)),
                ('Flight_Hours_Thres', models.CharField(blank=True, max_length=255, null=True)),
                ('Calendar_IntervalThres', models.FloatField(blank=True, null=True)),
                ('Calendar_Thres_Unit', models.CharField(blank=True, max_length=255, null=True)),
                ('Is_Notes_Thres', models.CharField(blank=True, max_length=255, null=True)),
                ('Flight_Cycle_IntervalRepeat', models.FloatField(blank=True, null=True)),
                ('Flight_Cycle_Repeat', models.CharField(blank=True, max_length=255, null=True)),
                ('Flight_Hours_IntervalRepeat', models.FloatField(blank=True, null=True)),
                ('Flight_Hours_Repeat', models.CharField(blank=True, max_length=255, null=True)),
                ('Calendar_IntervalRepeat', models.FloatField(blank=True, null=True)),
                ('Calendar_Repeat_Unit', models.CharField(blank=True, max_length=255, null=True)),
                ('Is_Notes_Repeat', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('Checks', models.CharField(default='null', max_length=255)),
            ],
            options={
                'verbose_name': 'Ready For Last Done Next Due',
            },
        ),
    ]
