# Generated by Django 4.2.7 on 2024-03-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMP', '0002_alter_exceldata_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceldata',
            old_name='Access',
            new_name='ACCESS',
        ),
        migrations.RenameField(
            model_name='exceldata',
            old_name='DY_Repeat',
            new_name='FH_Thres',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='DY_Thres',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='FH_lThres',
        ),
        migrations.AddField(
            model_name='exceldata',
            name='Calendar_Repeat',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='Calendar_Thres',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='Calendar_Unit_Repeat',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='Calendar_Unit_Thres',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='applicability_data',
            field=models.JSONField(default=dict),
        ),
    ]
