# Generated by Django 4.2.7 on 2024-03-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMP', '0003_rename_access_exceldata_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='TASK_TYPE',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
