# Generated by Django 4.2.7 on 2024-03-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMP', '0004_exceldata_task_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceldata',
            old_name='CHECKS',
            new_name='CHECK',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='applicability_data',
        ),
    ]
