# Generated by Django 4.2.7 on 2024-03-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMP', '0005_rename_checks_exceldata_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='dynamic_applicability',
            field=models.JSONField(default=dict),
        ),
    ]
