# Generated by Django 4.2.7 on 2024-03-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMP', '0007_dueclearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='CHECK',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='PACKAGE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
