# Generated by Django 4.2.7 on 2024-04-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMP', '0010_dueclearance_aircraft_amp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dueclearance',
            old_name='Aircraft_Amp',
            new_name='Aircraft_Clearance',
        ),
    ]
