# Generated by Django 4.2.7 on 2024-04-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMP', '0012_rename_aircraft_clearance_dueclearance_aircraft_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dueclearance',
            name='Aircraft_Name',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='Aircraft_Name',
        ),
    ]
