# Generated by Django 4.2.7 on 2024-05-09 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0018_rename_operator_name_aircraftdetails_airline_name'),
        ('AMP', '0014_exceldata_aircraft_name_exceldata_airline_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='Aircraft_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operator.aircraftdetails'),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='Airline_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operator.operatorinput'),
        ),
    ]
