# Generated by Django 4.2.7 on 2024-05-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0018_rename_operator_name_aircraftdetails_airline_name'),
        ('AMP', '0017_dueclearance_aircraft_name_dueclearance_airline_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceldata',
            name='Aircraft_Name',
        ),
        migrations.AddField(
            model_name='exceldata',
            name='Aircraft_Name',
            field=models.ManyToManyField(blank=True, to='Operator.aircraftdetails'),
        ),
    ]
