# Generated by Django 4.2.7 on 2024-05-12 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0018_rename_operator_name_aircraftdetails_airline_name'),
        ('AMP', '0018_remove_exceldata_aircraft_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceldata',
            name='Aircraft_Name',
        ),
        migrations.AddField(
            model_name='exceldata',
            name='Aircraft_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operator.aircraftdetails'),
        ),
    ]
