# Generated by Django 4.2.7 on 2024-05-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMP', '0023_remove_dueclearance_aircraft_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exceldata',
            options={'verbose_name': "AMP Data'"},
        ),
    ]
