# Generated by Django 4.2.7 on 2024-05-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMP', '0024_alter_exceldata_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceldata',
            old_name='ACESS_HOURS',
            new_name='ACCESS_HOURS',
        ),
    ]
