# Generated by Django 4.2.7 on 2024-06-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMP', '0025_rename_acess_hours_exceldata_access_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueclearance',
            name='DY_clearance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dueclearance',
            name='FC_clearance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dueclearance',
            name='FH_clearance',
            field=models.CharField(blank=True, default='0:00', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='ATTACHED_EO',
            field=models.CharField(default='xx-xxx-xx-xx', max_length=255),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='MPD_ITEM_NUMBER',
            field=models.CharField(default='xx-xxx-xx', max_length=255),
        ),
    ]
