# Generated by Django 4.2.7 on 2024-03-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FC_DY', models.FloatField(default=6.0)),
                ('FH_DY', models.FloatField(default=15.0)),
                ('Daily', models.FloatField(default=2.0)),
                ('Weekly', models.FloatField(default=7.0)),
                ('Service_DY', models.FloatField(default=60.0)),
                ('Service_FH', models.FloatField(default=500.0)),
                ('Service_FC', models.FloatField(default=250.0)),
                ('L_no', models.FloatField(default=5.0)),
                ('L1_DY', models.FloatField(default=120.0)),
                ('L1_FH', models.FloatField(default=900.0)),
                ('L1_FC', models.FloatField(default=360.0)),
                ('C_no', models.FloatField(default=10.0)),
                ('C1_YR', models.FloatField(default=2.0)),
                ('C1_FH', models.FloatField(default=6000.0)),
                ('C1_FC', models.FloatField(default=3000.0)),
            ],
        ),
    ]
