# Generated by Django 4.2.7 on 2024-03-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0002_operatorinput_num_aircrafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorinput',
            name='aircraft_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
