# Generated by Django 4.2.7 on 2024-03-01 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0003_operatorinput_aircraft_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorinput',
            name='aircraft_type',
        ),
    ]
