# Generated by Django 4.2.7 on 2024-03-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0007_aircraftdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatorinput',
            options={'verbose_name': "Operator Data'"},
        ),
    ]
