# Generated by Django 4.2.7 on 2024-03-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0008_alter_operatorinput_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraftdetails',
            options={'verbose_name': 'Aircraft Detail'},
        ),
        migrations.AlterModelOptions(
            name='operatorinput',
            options={'verbose_name': "Operator'"},
        ),
    ]
