# Generated by Django 4.2.7 on 2024-04-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0010_aircraftdetails_ac_bn_aircraftdetails_ac_ln_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorinput',
            name='Airline_Name',
            field=models.CharField(default='SkyLinker Airline', max_length=255),
        ),
    ]
