# Generated by Django 4.2.7 on 2024-05-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0015_alter_operatorinput_num_aircrafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftdetails',
            name='aircraft_name',
            field=models.CharField(default='SU-', max_length=100),
        ),
    ]
