# Generated by Django 4.2.7 on 2024-05-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0016_aircraftdetails_aircraft_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraftdetails',
            old_name='operator_input',
            new_name='operator_name',
        ),
    ]
