# Generated by Django 4.2.7 on 2024-05-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0018_rename_operator_name_aircraftdetails_airline_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraftdetails',
            old_name='Airline_Name',
            new_name='operator_input',
        ),
        migrations.RemoveField(
            model_name='aircraftdetails',
            name='aircraft_name',
        ),
    ]
