# Generated by Django 4.2.7 on 2024-05-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0019_rename_airline_name_aircraftdetails_operator_input_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorinput',
            name='Airline_Name',
        ),
    ]
