# Generated by Django 4.2.7 on 2024-05-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0020_remove_operatorinput_airline_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraftdetails',
            old_name='operator_input',
            new_name='Airline_Name',
        ),
        migrations.AddField(
            model_name='aircraftdetails',
            name='aircraft_name',
            field=models.CharField(default='SU-', max_length=100),
        ),
        migrations.AddField(
            model_name='operatorinput',
            name='Airline_Name',
            field=models.CharField(default='SkyLinker Airline', max_length=255),
        ),
    ]
