# Generated by Django 4.2.7 on 2024-05-20 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0021_rename_operator_input_aircraftdetails_airline_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftdetails',
            name='Airline_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operator.operatorinput', verbose_name='Airline Name'),
        ),
        migrations.AlterField(
            model_name='aircraftdetails',
            name='ac_bn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aircraft Block Number'),
        ),
        migrations.AlterField(
            model_name='aircraftdetails',
            name='ac_ln',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aircraft Line Number'),
        ),
        migrations.AlterField(
            model_name='aircraftdetails',
            name='ac_sn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aircraft Serial Number'),
        ),
        migrations.AlterField(
            model_name='aircraftdetails',
            name='aircraft_name',
            field=models.CharField(default='SU-', max_length=100, verbose_name='Aircraft Name'),
        ),
        migrations.AlterField(
            model_name='aircraftdetails',
            name='aircraft_type',
            field=models.CharField(max_length=100, verbose_name='Aircraft Type'),
        ),
        migrations.AlterField(
            model_name='aircraftdetails',
            name='production_date',
            field=models.DateField(verbose_name='Aircraft Production Date'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='Airline_Name',
            field=models.CharField(default='SkyLinker Airline', max_length=255, verbose_name='Airline Name'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='C1_FC',
            field=models.FloatField(default=3000.0, verbose_name='C11 Tasks Flight Cycles Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='C1_FH',
            field=models.FloatField(default=6000.0, verbose_name='C11 Tasks Flight Hours Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='C1_YR',
            field=models.FloatField(default=2.0, verbose_name='C1 Tasks Days Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='C_no',
            field=models.IntegerField(default=10, verbose_name='Number of C packages'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='Daily',
            field=models.FloatField(default=2.0, verbose_name='Daily Tasks Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='FC_DY',
            field=models.FloatField(default=6.0, verbose_name='Flight Cycle to Days Ratio'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='FH_DY',
            field=models.FloatField(default=15.0, verbose_name='Flight Hours to Days Ratio'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='L1_DY',
            field=models.FloatField(default=120.0, verbose_name='L1 Tasks Days Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='L1_FC',
            field=models.FloatField(default=360.0, verbose_name='L1 Tasks Flight Cycles Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='L1_FH',
            field=models.FloatField(default=900.0, verbose_name='L1 Tasks Flight Hours Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='L_no',
            field=models.IntegerField(default=5, verbose_name='Number of L packages'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='Service_DY',
            field=models.FloatField(default=60.0, verbose_name='Service Tasks Days Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='Service_FC',
            field=models.FloatField(default=250.0, verbose_name='Service Tasks Flight Cycles Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='Service_FH',
            field=models.FloatField(default=500.0, verbose_name='Service Tasks Flight Hours Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='Weekly',
            field=models.FloatField(default=7.0, verbose_name='Weekly Tasks Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='num_aircrafts',
            field=models.IntegerField(default=1, verbose_name='Number of Aircraft'),
        ),
    ]
