# Generated by Django 4.2.7 on 2024-05-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0022_alter_aircraftdetails_airline_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorinput',
            name='C1_FC',
            field=models.FloatField(default=3000.0, verbose_name='C11 Tasks FC Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='C1_FH',
            field=models.FloatField(default=6000.0, verbose_name='C11 Tasks FH Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='C1_YR',
            field=models.FloatField(default=2.0, verbose_name='C1 Tasks DY Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='FC_DY',
            field=models.FloatField(default=6.0, verbose_name='FC To DY Ratio'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='FH_DY',
            field=models.FloatField(default=15.0, verbose_name='FH to DY Ratio'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='L1_DY',
            field=models.FloatField(default=120.0, verbose_name='L1 Tasks DY Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='L1_FC',
            field=models.FloatField(default=360.0, verbose_name='L1 Tasks FC Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='L1_FH',
            field=models.FloatField(default=900.0, verbose_name='L1 Tasks FH Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='Service_DY',
            field=models.FloatField(default=60.0, verbose_name='Service Tasks DY Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='Service_FC',
            field=models.FloatField(default=250.0, verbose_name='Service Tasks FC Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='Service_FH',
            field=models.FloatField(default=500.0, verbose_name='Service Tasks FH Interval'),
        ),
    ]
