# Generated by Django 4.2.7 on 2024-05-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0023_alter_operatorinput_c1_fc_alter_operatorinput_c1_fh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorinput',
            name='C1_FC',
            field=models.FloatField(default=3000.0, verbose_name='C1 Tasks FC Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='C1_FH',
            field=models.FloatField(default=6000.0, verbose_name='C1 Tasks FH Interval'),
        ),
    ]
