# Generated by Django 4.2.7 on 2024-05-22 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Operator', '0024_alter_operatorinput_c1_fc_alter_operatorinput_c1_fh'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorinput',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
