# Generated by Django 4.2.7 on 2024-05-22 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0025_operatorinput_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorinput',
            name='user',
        ),
    ]
