# Generated by Django 4.2.7 on 2024-06-09 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0026_remove_operatorinput_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftdetails',
            name='ac_bn',
            field=models.CharField(blank=True, default='xxxxx', max_length=255, null=True, verbose_name='Aircraft Block Number'),
        ),
        migrations.AlterField(
            model_name='aircraftdetails',
            name='ac_ln',
            field=models.CharField(blank=True, default='xxxx', max_length=255, null=True, verbose_name='Aircraft Line Number'),
        ),
        migrations.AlterField(
            model_name='aircraftdetails',
            name='ac_sn',
            field=models.CharField(blank=True, default='xxxxx', max_length=255, null=True, verbose_name='Aircraft Serial Number'),
        ),
        migrations.AlterField(
            model_name='aircraftdetails',
            name='aircraft_type',
            field=models.CharField(default='B737-', max_length=100, verbose_name='Aircraft Type'),
        ),
        migrations.AlterField(
            model_name='aircraftdetails',
            name='production_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Aircraft Production Date'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='C1_FC',
            field=models.FloatField(default=3000.0, verbose_name='C1 Task FC Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='C1_FH',
            field=models.FloatField(default=6000.0, verbose_name='C1 Task FH Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='Daily',
            field=models.FloatField(default=2.0, verbose_name='Daily Task Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='L1_DY',
            field=models.FloatField(default=120.0, verbose_name='L1 Task DY Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='L1_FC',
            field=models.FloatField(default=360.0, verbose_name='L1 Task FC Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='L1_FH',
            field=models.FloatField(default=900.0, verbose_name='L1 Task FH Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='Service_DY',
            field=models.FloatField(default=60.0, verbose_name='Service Task DY Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='Service_FC',
            field=models.FloatField(default=250.0, verbose_name='Service Task FC Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='Service_FH',
            field=models.FloatField(default=500.0, verbose_name='Service Task FH Interval'),
        ),
        migrations.AlterField(
            model_name='operatorinput',
            name='Weekly',
            field=models.FloatField(default=7.0, verbose_name='Weekly Task Interval'),
        ),
    ]
