# Generated by Django 4.2.7 on 2024-03-13 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AMP', '0006_exceldata_dynamic_applicability'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_done_date', models.DateField()),
                ('last_done_fh', models.FloatField()),
                ('last_done_fc', models.FloatField()),
                ('excel_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMP.exceldata')),
            ],
        ),
    ]
