# Generated by Django 4.2.7 on 2024-03-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDND', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastdone',
            name='last_done_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='last_done_fc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='last_done_fh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
