# Generated by Django 4.2.7 on 2024-03-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDND', '0002_alter_lastdone_last_done_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastdone',
            name='al_nd_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastdone',
            name='al_nd_fc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastdone',
            name='al_nd_fh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastdone',
            name='done',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='lastdone',
            name='mpd_nd_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastdone',
            name='mpd_nd_fc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastdone',
            name='mpd_nd_fh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
