# Generated by Django 4.2.7 on 2024-03-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDND', '0003_lastdone_al_nd_date_lastdone_al_nd_fc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastdone',
            name='al_nd_fh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='last_done_fh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='mpd_nd_fh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
