# Generated by Django 4.2.7 on 2024-03-17 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDND', '0004_alter_lastdone_al_nd_fh_alter_lastdone_last_done_fh_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastdone',
            options={'verbose_name': 'Last Done Next Due'},
        ),
        migrations.CreateModel(
            name='DueClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DY_clearance', models.IntegerField(blank=True, null=True)),
                ('FH_clearance', models.CharField(blank=True, max_length=255, null=True)),
                ('FC_clearance', models.IntegerField(blank=True, null=True)),
                ('clearance_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LDND.lastdone')),
            ],
            options={
                'verbose_name': 'Due Clearance',
            },
        ),
    ]
