# Generated by Django 4.2.7 on 2024-03-17 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LDND', '0005_alter_lastdone_options_dueclearance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dueclearance',
            name='clearance_input',
        ),
    ]
