# Generated by Django 4.2.7 on 2024-03-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDND', '0007_lastdone_due_clearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastdone',
            name='al_due',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lastdone',
            name='mpd_due',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
