# Generated by Django 4.2.7 on 2024-03-17 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LDND', '0008_lastdone_al_due_lastdone_mpd_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastdone',
            name='due_clearance',
        ),
        migrations.DeleteModel(
            name='DueClearance',
        ),
    ]
