# Generated by Django 4.2.7 on 2024-03-24 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LDND', '0010_changelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'permissions': [('access_changelog', 'Can access change logs')]},
        ),
    ]
