# Generated by Django 4.2.7 on 2024-03-24 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LDND', '0011_alter_changelog_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeLog',
        ),
    ]
