# Generated by Django 4.2.7 on 2024-03-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDND', '0014_lastdone_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastdone',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='ChangeLog',
        ),
    ]
