# Generated by Django 4.2.7 on 2024-05-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDND', '0015_lastdone_modified_on_delete_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastdone',
            name='aircraft_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lastdone',
            name='airline_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
