# Generated by Django 4.2.7 on 2024-05-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDND', '0017_remove_lastdone_aircraft_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastdone',
            name='Aircraft_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='Airline_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
