# Generated by Django 4.2.7 on 2024-05-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0024_alter_operatorinput_c1_fc_alter_operatorinput_c1_fh'),
        ('AMP', '0025_rename_acess_hours_exceldata_access_hours'),
        ('LDND', '0019_alter_lastdone_aircraft_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastdone',
            name='Aircraft_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operator.aircraftdetails', verbose_name='Aircraft Name'),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='Airline_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operator.operatorinput', verbose_name='Airline Name'),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='al_due',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Airline DUE'),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='al_nd_date',
            field=models.DateField(blank=True, null=True, verbose_name='Airline ND DATE'),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='al_nd_fc',
            field=models.FloatField(blank=True, null=True, verbose_name='Airline ND FC'),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='al_nd_fh',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Airline ND FH'),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='done',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Done'),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='excel_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMP.exceldata', verbose_name='MPD Item No.'),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='last_done_date',
            field=models.DateField(blank=True, null=True, verbose_name='LD Date'),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='last_done_fc',
            field=models.FloatField(blank=True, null=True, verbose_name='LD FC'),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='last_done_fh',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LD FH'),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='mpd_due',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MPD DUE'),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='mpd_nd_date',
            field=models.DateField(blank=True, null=True, verbose_name='MPD ND DATE'),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='mpd_nd_fc',
            field=models.FloatField(blank=True, null=True, verbose_name='MPD ND FC'),
        ),
        migrations.AlterField(
            model_name='lastdone',
            name='mpd_nd_fh',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MPD ND FH'),
        ),
    ]
