# Generated by Django 4.2.7 on 2024-03-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField()),
                ('current_flight_hours', models.CharField(max_length=10)),
                ('current_flight_cycles', models.IntegerField()),
                ('apu_ratio', models.FloatField()),
            ],
        ),
    ]
