# Generated by Django 4.2.7 on 2024-03-02 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AircraftData', '0002_delete_aircraftdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(default=datetime.datetime.now)),
                ('current_flight_hours', models.CharField(max_length=10)),
                ('current_flight_cycles', models.IntegerField()),
                ('apu_hours_to_flight_hours_ratio', models.FloatField()),
            ],
        ),
    ]
