# Generated by Django 4.2.7 on 2024-03-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AircraftData', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraftdata',
            options={'verbose_name': "Aircraft'"},
        ),
    ]
