# Generated by Django 4.2.7 on 2024-03-17 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AircraftData', '0005_aircraftdata_apu_fc_aircraftdata_apu_fh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_sn', models.CharField(max_length=100)),
                ('eng_fh', models.CharField(blank=True, max_length=255, null=True)),
                ('eng_fc', models.IntegerField(blank=True, null=True)),
                ('aircraft_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AircraftData.aircraftdata')),
            ],
            options={
                'verbose_name': 'Engines Detail',
            },
        ),
    ]
