# Generated by Django 4.2.7 on 2024-04-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AircraftData', '0006_enginedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftdata',
            name='Aircraft_Name',
            field=models.CharField(default='SU-', max_length=255),
        ),
    ]
