# Generated by Django 4.2.7 on 2024-05-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AircraftData', '0007_aircraftdata_aircraft_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraftdata',
            name='Aircraft_Name',
        ),
        migrations.RemoveField(
            model_name='enginedetails',
            name='aircraft_input',
        ),
    ]
