# Generated by Django 4.2.7 on 2024-05-09 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0017_rename_operator_input_aircraftdetails_operator_name'),
        ('AircraftData', '0009_aircraftdata_aircraft_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftdata',
            name='Airline_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operator.operatorinput'),
        ),
    ]
