# Generated by Django 4.2.7 on 2024-05-09 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0018_rename_operator_name_aircraftdetails_airline_name'),
        ('AircraftData', '0010_aircraftdata_airline_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginedetails',
            name='Aircraft_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operator.aircraftdetails'),
        ),
        migrations.AddField(
            model_name='enginedetails',
            name='Airline_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operator.operatorinput'),
        ),
    ]
