# Generated by Django 4.2.7 on 2024-05-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AircraftData', '0011_enginedetails_aircraft_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftdata',
            name='current_flight_cycles',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
