# Generated by Django 4.2.7 on 2024-05-12 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AircraftData', '0012_alter_aircraftdata_current_flight_cycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginedetails',
            name='Aircraft_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AircraftData.aircraftdata'),
        ),
    ]
