# Generated by Django 4.2.7 on 2024-05-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AircraftData', '0014_rename_aircraft_name_enginedetails_aircraft_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftdata',
            name='current_flight_cycles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='current_flight_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
