# Generated by Django 4.2.7 on 2024-05-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AircraftData', '0015_alter_aircraftdata_current_flight_cycles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraftdata',
            name='Aircraft_Name',
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='current_flight_cycles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='current_flight_hours',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='enginedetails',
            name='aircraft_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AircraftData.aircraftdata'),
        ),
    ]
