# Generated by Django 4.2.7 on 2024-05-20 13:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0024_alter_operatorinput_c1_fc_alter_operatorinput_c1_fh'),
        ('AircraftData', '0018_rename_aircraft_input_enginedetails_aircraft_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftdata',
            name='Aircraft_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operator.aircraftdetails', verbose_name='Aircraft Name'),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='Airline_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operator.operatorinput', verbose_name='Airline Name'),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='apu_fc',
            field=models.IntegerField(blank=True, null=True, verbose_name='APU Flight Cycles'),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='apu_fh',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='APU Flight Hours'),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='apu_hours_to_flight_hours_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='APU FH To AC Fh Ratio'),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='apu_sn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='APU Serial Number'),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='current_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Current Entry Date'),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='current_flight_cycles',
            field=models.IntegerField(blank=True, null=True, verbose_name='Current Flight Cycles'),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='current_flight_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Flight Hours'),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='num_engs',
            field=models.IntegerField(default=1, verbose_name='Number of Engines'),
        ),
        migrations.AlterField(
            model_name='enginedetails',
            name='Aircraft_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AircraftData.aircraftdata', verbose_name='Aircraft Name'),
        ),
        migrations.AlterField(
            model_name='enginedetails',
            name='Airline_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operator.operatorinput', verbose_name='Airline Name'),
        ),
        migrations.AlterField(
            model_name='enginedetails',
            name='eng_fc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Engine Flight Cycles'),
        ),
        migrations.AlterField(
            model_name='enginedetails',
            name='eng_fh',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Engine Flight Hours'),
        ),
        migrations.AlterField(
            model_name='enginedetails',
            name='eng_sn',
            field=models.CharField(max_length=100, verbose_name='Engine Serial Number'),
        ),
    ]
