# Generated by Django 4.2.7 on 2024-06-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AircraftData', '0019_alter_aircraftdata_aircraft_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftdata',
            name='apu_fc',
            field=models.IntegerField(blank=True, default=17000, null=True, verbose_name='APU Flight Cycles'),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='apu_fh',
            field=models.CharField(blank=True, default='25000:00', max_length=255, null=True, verbose_name='APU Flight Hours'),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='apu_sn',
            field=models.CharField(blank=True, default='X0000', max_length=255, null=True, verbose_name='APU Serial Number'),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='current_flight_cycles',
            field=models.IntegerField(blank=True, default=15000, null=True, verbose_name='Current Total Flight Cycles'),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='current_flight_hours',
            field=models.CharField(blank=True, default='40000:00', max_length=255, null=True, verbose_name='Current Total Flight Hours'),
        ),
        migrations.AlterField(
            model_name='enginedetails',
            name='eng_fc',
            field=models.IntegerField(blank=True, default=18000, null=True, verbose_name='Engine Flight Cycles'),
        ),
        migrations.AlterField(
            model_name='enginedetails',
            name='eng_fh',
            field=models.CharField(blank=True, default='40000:00', max_length=255, null=True, verbose_name='Engine Flight Hours'),
        ),
        migrations.AlterField(
            model_name='enginedetails',
            name='eng_sn',
            field=models.CharField(default='000000', max_length=100, verbose_name='Engine Serial Number'),
        ),
    ]
