# Generated by Django 4.2.7 on 2024-06-09 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AircraftData', '0021_alter_aircraftdata_apu_hours_to_flight_hours_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftdata',
            name='current_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data Entry Date'),
        ),
    ]
